#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Buildout ticket 07: the Cloudflare steps that put the site on barmadden.com, from the deploy ticket's dashboard
# checklist. Run it from the repo root with `bash scripts/cloudflare-setup.sh`. Stages check what they can with dig and
# curl, so a re-run shows what's already done; Enter skips past a stage that is.

TOTAL_STAGES=9
DOMAIN=barmadden.com
DASH=https://dash.cloudflare.com/3edd4b87aa844db287c56527fb8dba69
# The analytics token stays outside the repo; `npm run usage` loads this file.
ENV_FILE="$HOME/.config/barmadden/.env"

# check "label" command...: runs a check and prints a tick or a cross; never stops the wizard.
check() {
  local label="$1"; shift
  if "$@" >/dev/null 2>&1; then printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"
  else printf '  %s✗ %s%s\n' "$RED" "$label" "$RESET"; fi
}
resolves() { [[ -n "$(dig +short "$@")" ]]; }
status() { curl -s -o /dev/null -w '%{http_code}' "$@"; }
# blocked curl-args...: /ws answers 403 from the WAF. The Worker's own refusal is the plain text "bad origin".
blocked() {
  local out; out=$(curl -s -w '\n%{http_code}' -H 'Upgrade: websocket' "$@" "https://$DOMAIN/ws/overworld")
  [[ ${out##*$'\n'} == 403 && $out != 'bad origin'* ]]
}
no_ga() { ! grep -q googletagmanager <<<"$(curl -s "$1")"; }
# One bot test for the WAF's socket rule and the page's bot flag, so the two always agree.
BOTS='cf.client.bot or lower(http.user_agent) contains "bot/" or lower(http.user_agent) contains "spider" or lower(http.user_agent) contains "crawl" or lower(http.user_agent) contains "headless"'
# flagged curl-args...: the home page comes back with the edge's bot flag, Server-Timing: bot.
flagged() { grep -qi '^server-timing:.*bot' <<<"$(curl -sI "$@" "https://$DOMAIN/")"; }
GOOGLEBOT='Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
bot_flag_works() { flagged -A "$GOOGLEBOT" && ! flagged; }
# www_redirects: https://www answers 301 to the same path and query on the apex.
www_redirects() {
  [[ $(curl -s -o /dev/null -w '%{http_code} %{redirect_url}' "https://www.$DOMAIN/midtown/foundry?x=1") \
    == "301 https://$DOMAIN/midtown/foundry?x=1" ]]
}

banner "barmadden.com on Cloudflare"

stage "Zone active, mail intact, old site gone"
say "The nameservers already point at Cloudflare. Confirm the zone is Active and Google Workspace mail survived."
open_url "$DASH/$DOMAIN"
step "The zone's Overview should say Active. If it still says Pending, use 'Check nameservers now'."
say ""
say "What the world sees now:"
note "NS     $(dig +short NS $DOMAIN | tr '\n' ' ')"
note "MX     $(dig +short MX $DOMAIN | wc -l | tr -d ' ') records, lowest: $(dig +short MX $DOMAIN | sort -n | head -1)"
note "TXT    $(dig +short TXT $DOMAIN | tr '\n' ' ' | grep . || echo none)"
note "DKIM   $(dig +short TXT google._domainkey.$DOMAIN | cut -c1-32)..."
note "DMARC  $(dig +short TXT _dmarc.$DOMAIN | grep . || echo none)"
note "DS     $(dig +short DS $DOMAIN | grep . || echo 'none (DNSSEC off at GoDaddy, as it should be)')"
step "Compare with GoDaddy's DNS page for $DOMAIN, which still lists the old records. Any MX or TXT there"
note "  (SPF v=spf1..., google-site-verification=..., _dmarc) missing above: add it under DNS → Records here."
if ! grep -q spf1 <<<"$(dig +short TXT $DOMAIN)"; then
  warn "No SPF record, and Google Workspace is the only sender. Add it under DNS → Records → Add record:"
  note "  Type TXT, Name @, Content v=spf1 include:_spf.google.com ~all → Save."
fi
if resolves A $DOMAIN || resolves AAAA $DOMAIN || resolves www.$DOMAIN || resolves AAAA www.$DOMAIN; then
  warn "$DOMAIN or www answers. Before stage 3, delete any A, AAAA or CNAME named @ or www under DNS → Records"
  note "  that points at the old host (leave MX and TXT alone). After stage 3 these are Cloudflare's own addresses."
else
  note "No A, AAAA or CNAME at $DOMAIN or www: no old site to clear."
fi
say ""
step "Send a test email to your Workspace address from another account, then reply to it."
pause "Zone Active and the email went both ways? Press Enter."

stage "Log wrangler in and deploy the Worker"
say "The Worker has never been deployed. This logs wrangler in (a browser tab asks you to allow it), then runs"
say "the type-checks, build and tests and deploys. Production has workers_dev off, so it has no URL until stage 3."
if confirm "Run wrangler login (if needed), then npm run ci && npx wrangler deploy?"; then
  grep -q 'You are logged in' <<<"$(npx wrangler whoami 2>/dev/null)" || npx wrangler login
  npm run ci && npx wrangler deploy || warn "The checks or the deploy failed: fix what it printed, then re-run this stage."
fi
pause

stage "Attach barmadden.com to the Worker"
open_url "$DASH/workers/services/view/barmadden/production/settings"
step "Domains & Routes → Add → Custom domain → $DOMAIN → Add domain."
note "Cloudflare adds the DNS record and the certificate itself; the first answer can take a few minutes."
note "wrangler.toml declares no custom domain, so later deploys leave this one alone."
pause "Added? Press Enter to check."
check "https://$DOMAIN answers 200" test "$(status https://$DOMAIN/)" = 200
pause

stage "Redirect www to the apex"
open_url "$DASH/$DOMAIN/dns/records"
step "Add record: type AAAA, name www, IPv6 address 100::, Proxy status Proxied (orange cloud) → Save."
note "100:: goes nowhere; the record only lets Cloudflare answer for www so the rule below can redirect it."
open_url "$DASH/$DOMAIN/rules/overview"
step "Templates → Redirect from WWW to root → it fills Wildcard pattern, Request URL https://www.* and"
note "  Target URL https://\${1}. Status code 301, Preserve query string on → Deploy."
open_url "$DASH/$DOMAIN/ssl-tls/edge-certificates"
step "Always Use HTTPS → on, so http:// (www or not) moves to https:// before the rule above."
pause "Done? Press Enter to check."
check "https://www redirects 301 to the apex, path and query kept" www_redirects
check "http://www ends up on https://$DOMAIN" \
  test "$(curl -sL -o /dev/null -w '%{url_effective}' "http://www.$DOMAIN/")" = "https://$DOMAIN/"
pause

stage "Connect Workers Builds"
open_url "$DASH/workers/services/view/barmadden/production/settings"
step "Builds → Connect → GitHub → obj63mc/portfolio (install the Cloudflare app on the repo if asked)."
step "Production branch: main. Branch control: Enable Preview Builds (builds for non-production branches)."
step "Build command:   npm run ci"
step "Deploy command:  npx wrangler deploy          Preview command:  npx wrangler preview"
step "Build variables: PUBLIC_GA_ID = your GA4 measurement ID (G-...), or leave it out until you have one."
note "The build passes PUBLIC_GA_ID into the site only on main, so Previews never load GA."
note "If the page offers 'Switch to Worker Previews', take it: it's one-time and gives each PR its own Preview."
pause "Connected? Press Enter. The next push to main deploys by itself."

stage "WAF rules: the socket is for browsers on this site"
say "Two custom rules (of the Free plan's 5). A blocked request never reaches the Worker, so it costs nothing."
open_url "$DASH/$DOMAIN/security/security-rules"
step "Create rule → Custom rules. Name: socket origin. Edit expression, paste, action Block → Deploy:"
note '  starts_with(http.request.uri.path, "/ws") and not any(http.request.headers["origin"][*] eq "https://barmadden.com")'
step "Create another. Name: socket bots. Edit expression, paste, action Block → Deploy:"
note "  starts_with(http.request.uri.path, \"/ws\") and ($BOTS)"
pause "Deployed both? Press Enter to check."
check "/ws with a foreign Origin is blocked at the edge" blocked -H 'Origin: https://evil.example'
check "/ws from a bot's user agent is blocked at the edge" blocked -A "$GOOGLEBOT" -H "Origin: https://$DOMAIN"
pause

stage "Bot flag for the page, AI bot policies"
say "Bots still read every page. The same bot test adds Server-Timing: bot to their responses, which the page's"
say "script can read, so a bot's page never opens a socket at all (ticket 13 builds that side)."
open_url "$DASH/$DOMAIN/rules/overview"
step "Create rule → Response Header Transform Rule. Name: bot flag. Custom filter expression → Edit expression:"
note "  $BOTS"
step "Modify response header: Add static, Header name Server-Timing, Value bot → Deploy."
say ""
open_url "$DASH/$DOMAIN/security/settings"
step "Filter Bot traffic. Configure AI bot policies: Training → Block (on all pages); Search → Allow; Agent → Allow."
step "Optional, same page: 'block training in robots.txt' → on (Cloudflare serves the robots.txt lines)."
step "Bot fight mode → leave off. On Free it can't be scoped and would challenge the socket and crawlers."
pause "Done? Press Enter to check."
check "a bot's user agent gets Server-Timing: bot on pages, a browser's doesn't" bot_flag_works
pause

stage "Analytics token for npm run usage"
say "npm run usage reads month-to-date Durable Object usage with a read-only analytics token."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → Custom token → Get started. Name it barmadden usage."
step "Permissions: Account · Account Analytics · Read. Account Resources: Include · your account."
step "Continue to summary → Create Token, then copy the token (it's shown once)."
ask_secret CF_ANALYTICS_TOKEN "Paste the token:"
mkdir -p "$(dirname "$ENV_FILE")"
write_env CF_ANALYTICS_TOKEN "$CF_ANALYTICS_TOKEN"
chmod 600 "$ENV_FILE"
say ""
npm run --silent usage || warn "npm run usage failed; check the token's permission and account."
pause

stage "Verify"
say "Checking the live site from here:"
check "https://$DOMAIN serves the site (200)" test "$(status https://$DOMAIN/)" = 200
check "https://www redirects 301 to the apex, path and query kept" www_redirects
check "/ws with a foreign Origin is blocked at the edge" blocked -H 'Origin: https://evil.example'
check "/ws from a bot's user agent is blocked at the edge" blocked -A "$GOOGLEBOT" -H "Origin: https://$DOMAIN"
check "CF_ANALYTICS_TOKEN is stored outside the repo ($ENV_FILE)" grep -q '^CF_ANALYTICS_TOKEN=.' "$ENV_FILE"
check "/ws from headless Chrome is blocked at the edge" blocked -A 'HeadlessChrome/140.0.0.0' -H "Origin: https://$DOMAIN"
check "a bot's user agent gets Server-Timing: bot on pages, a browser's doesn't" bot_flag_works
say ""
step "Open a PR from any branch: Workers Builds comments a Preview URL on it."
ask PREVIEW_URL "Paste the Preview URL (Enter skips if there's no PR yet):"
if [[ -n "$PREVIEW_URL" ]]; then
  check "the Preview sends X-Robots-Tag: noindex" grep -qi '^x-robots-tag: noindex' <<<"$(curl -sI "$PREVIEW_URL")"
  check "the Preview's page loads no GA" no_ga "$PREVIEW_URL"
fi
say ""
say "By hand:"
step "Once the client joins rooms (ticket 13): a phone and a desktop see each other at https://$DOMAIN;"
note "  npm run multiplayer:off drops both to solo, npm run multiplayer:on brings them back."
pause "Done? Press Enter for the summary."

finish
